# ----------------------------------------------------
# SFML 3 MAKEFILE
# ----------------------------------------------------

# CHANGE THIS PATH to where you extracted SFML 3
# Example: C:/Users/YourName/Downloads/SFML-3.0.0
SFML_DIR = C:/libraries/SFML-3.0.2

# Compiler settings
CXX = g++
# We use -I to point to SFML 3 include BEFORE system includes
CXXFLAGS = -std=c++17 -Wall -Iinclude -I$(SFML_DIR)/include

# Library paths
# We use -L to point to SFML 3 libs
LDFLAGS = -L$(SFML_DIR)/lib

# SFML 3 Libraries
LIBS = -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio

# Source files
SRCS = main.cpp Game.cpp Board.cpp Character.cpp Controller.cpp Doors.cpp Gates.cpp LevelSelect.cpp

# Object files
OBJS = $(SRCS:.cpp=.o)

# Executable name
TARGET = game.exe

# Default target
all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(OBJS) -o $(TARGET) $(LDFLAGS) $(LIBS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	del *.o $(TARGET)
